const toNumber = (value, fallback = 0) => {
  const numeric = Number(value)
  return Number.isFinite(numeric) ? numeric : fallback
}

export const buildPerfectPrototypeSupportBoundaryExpertUnsat = ({
  reason = "unsat_no_local_experts",
  reasonCounts = {},
  familySummary = {},
  groupDatasetSummary = {},
  localExpertCandidateCount = 0,
  localExpertQualifiedCount = 0,
  qualifiedExpertDistinctMatchedDateSignatureCount = 0,
  qualifiedExpertDistinctMatchedMonthSignatureCount = 0,
  qualifiedExpertDistinctMatchedFoldSignatureCount = 0,
  expertUnionCandidateCount = 0,
  expertUnionQualifiedCount = 0,
  coverageFrontierCandidateCount = 0,
  coverageFrontierQualifiedCount = 0,
  distinctMatchedDateSignatureCount = 0,
  distinctMatchedMonthSignatureCount = 0,
  distinctMatchedFoldSignatureCount = 0,
  bestSingleExpertTrainMatchedDateCount = 0,
  bestSingleExpertTrainMatchedMonthCount = 0,
  bestSingleExpertTrainMatchedFoldCount = 0,
  expertUnionDateGainOverBestSingleExpert = 0,
  expertUnionMonthGainOverBestSingleExpert = 0,
  expertUnionFoldGainOverBestSingleExpert = 0,
  supportFitExcluded = false,
  supportLeaveOneOutRecovered = false,
  bestTrainSummary = null,
  bestOosSummary = null,
  candidatesEvaluated = [],
} = {}) => ({
  ok: false,
  reason,
  supportFitExcluded: supportFitExcluded === true,
  supportLeaveOneOutRecovered: supportLeaveOneOutRecovered === true,
  ordinalMotifFeatureCount: toNumber(familySummary?.ordinalMotifFeatureCount, 0),
  ordinalMotifGroupCount: toNumber(familySummary?.ordinalMotifGroupCount, 0),
  corridorPositiveBasinCount: toNumber(familySummary?.corridorPositiveBasinCount, 0),
  corridorPositiveEligibleBasinCount: toNumber(familySummary?.corridorPositiveEligibleBasinCount, 0),
  corridorPositiveSeedCount: toNumber(familySummary?.corridorPositiveSeedCount, 0),
  supportCaseReachableBasinCount: toNumber(familySummary?.supportCaseReachableBasinCount, 0),
  carrierGraphFeatureCount: toNumber(familySummary?.carrierGraphFeatureCount, 0),
  carrierComponentCount: toNumber(familySummary?.carrierComponentCount, 0),
  carrierEligibleComponentCount: toNumber(familySummary?.carrierEligibleComponentCount, 0),
  supportCaseReachableComponentCount: toNumber(familySummary?.supportCaseReachableComponentCount, 0),
  recurrencePurityFeatureCount: toNumber(familySummary?.recurrencePurityFeatureCount, 0),
  recurrencePurityGroupCount: toNumber(familySummary?.recurrencePurityGroupCount, 0),
  boundaryGroupCount: toNumber(groupDatasetSummary?.boundaryGroupCount, 0),
  boundaryGroupEligibleCount: toNumber(groupDatasetSummary?.boundaryGroupEligibleCount, 0),
  localExpertCandidateCount: toNumber(localExpertCandidateCount, 0),
  localExpertQualifiedCount: toNumber(localExpertQualifiedCount, 0),
  qualifiedExpertDistinctMatchedDateSignatureCount: toNumber(qualifiedExpertDistinctMatchedDateSignatureCount, 0),
  qualifiedExpertDistinctMatchedMonthSignatureCount: toNumber(qualifiedExpertDistinctMatchedMonthSignatureCount, 0),
  qualifiedExpertDistinctMatchedFoldSignatureCount: toNumber(qualifiedExpertDistinctMatchedFoldSignatureCount, 0),
  expertUnionCandidateCount: toNumber(expertUnionCandidateCount, 0),
  expertUnionQualifiedCount: toNumber(expertUnionQualifiedCount, 0),
  coverageFrontierCandidateCount: toNumber(coverageFrontierCandidateCount, 0),
  coverageFrontierQualifiedCount: toNumber(coverageFrontierQualifiedCount, 0),
  distinctMatchedDateSignatureCount: toNumber(distinctMatchedDateSignatureCount, 0),
  distinctMatchedMonthSignatureCount: toNumber(distinctMatchedMonthSignatureCount, 0),
  distinctMatchedFoldSignatureCount: toNumber(distinctMatchedFoldSignatureCount, 0),
  bestSingleExpertTrainMatchedDateCount: toNumber(bestSingleExpertTrainMatchedDateCount, 0),
  bestSingleExpertTrainMatchedMonthCount: toNumber(bestSingleExpertTrainMatchedMonthCount, 0),
  bestSingleExpertTrainMatchedFoldCount: toNumber(bestSingleExpertTrainMatchedFoldCount, 0),
  expertUnionDateGainOverBestSingleExpert: toNumber(expertUnionDateGainOverBestSingleExpert, 0),
  expertUnionMonthGainOverBestSingleExpert: toNumber(expertUnionMonthGainOverBestSingleExpert, 0),
  expertUnionFoldGainOverBestSingleExpert: toNumber(expertUnionFoldGainOverBestSingleExpert, 0),
  unsatReasonCounts: reasonCounts,
  bestTrainSummary,
  bestOosSummary,
  candidatesEvaluated,
})
