export const buildStepCShapingStateManifest = async ({
  permanentDropListPath,
  permanentDropCount,
  commonStatePath,
  commonStateApplied,
  commonStateSource,
  candidateMode,
  c0Enabled,
  c0InputMode,
  c0ShortlistedFamilyCount,
  c0FallbackUsed,
  c1Enabled,
  c1PassedFamilyCount,
  c1FallbackUsed,
  c1ProbeScope,
  c1ProbeProfile,
  c2Enabled,
  c2RepresentativeFamilyCount,
  c2FallbackUsed,
  c2SimilarityPolicy,
  c2RepresentativePolicy,
  previousRunEAssistWeight,
  previousRunEAssistThreshold,
  salvagePoolPath,
  salvageBoostCount,
  salvagePenaltyCount,
  quarantinePoolPath,
  quarantineCount
}) => ({
  version: 1,
  generatedAt: new Date().toISOString(),
  permanentDropListPath: permanentDropListPath ?? null,
  permanentDropCount: Math.max(0, Number(permanentDropCount ?? 0) || 0),
  commonStatePath: commonStatePath ?? null,
  commonStateApplied: commonStateApplied === true,
  commonStateSource: commonStateSource ?? null,
  candidateMode: candidateMode ?? null,
  c0Enabled: c0Enabled === true,
  c0InputMode: c0InputMode ?? null,
  c0ShortlistedFamilyCount: Math.max(0, Number(c0ShortlistedFamilyCount ?? 0) || 0),
  c0FallbackUsed: c0FallbackUsed === true,
  c1Enabled: c1Enabled === true,
  c1PassedFamilyCount: Math.max(0, Number(c1PassedFamilyCount ?? 0) || 0),
  c1FallbackUsed: c1FallbackUsed === true,
  c1ProbeScope: c1ProbeScope ?? null,
  c1ProbeProfile: c1ProbeProfile ?? null,
  c2Enabled: c2Enabled === true,
  c2RepresentativeFamilyCount: Math.max(0, Number(c2RepresentativeFamilyCount ?? 0) || 0),
  c2FallbackUsed: c2FallbackUsed === true,
  c2SimilarityPolicy: c2SimilarityPolicy ?? null,
  c2RepresentativePolicy: c2RepresentativePolicy ?? null,
  previousRunEAssistWeight: Math.max(0, Number(previousRunEAssistWeight ?? 0) || 0),
  previousRunEAssistThreshold: Math.max(0, Number(previousRunEAssistThreshold ?? 0) || 0),
  salvagePoolPath: salvagePoolPath ?? null,
  salvageBoostCount: Math.max(0, Number(salvageBoostCount ?? 0) || 0),
  salvagePenaltyCount: Math.max(0, Number(salvagePenaltyCount ?? 0) || 0),
  quarantinePoolPath: quarantinePoolPath ?? null,
  quarantineCount: Math.max(0, Number(quarantineCount ?? 0) || 0)
})
